apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-nonprod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgCHmM9cYckSIMY7dHZOEBJt5t74X/Hqyncb95MwOM+OnBJ3jvlysbjZH5OdIx9M6lWPLdDRvg7RCROv+sqZkBGC3k0yemzfVOr79gYIEtQeQ8mYSGsQINJmG4k+Hg8JtFx4lrZ148s8CUfeXZQCVvoEM03U7qJO4NoUSVb7huyVe346OYQZUKdtlUa8T8CLvzhprU3zYToyHU0sLCbbpFdg8hOn6NlQ3CT1sMci3gN5QGnul2084X78CVBj+rrMiOZlzLUC9iR+UEAKZKsc5pMXqBJOP34Ll/9VJ3oM4hnFoENBD6T24hPpk2sS7dbE8LpHnvm5W02J62IHEOGgetPMZSYh3++WzChDe20BIiAlI71SuqPsI7a9vD9s8AUYCv/1BBT9OlfqRI4Q32IcKQTeQ/SNG3L+GX+k3aaim/FyxLsVhLnrZTbl6RzJa5AiZiyw1HN3F42rpa1xGF6CWlPYeDP+zJnuHaQ+rN/sd0Ve/GYtA6Ko+kjtu68RiwUBIig53VwU0TJ5OJ8s/aTGGsoI/aYXpGqYSP21gN00CMnQ68jzhmYuOpki0rkBFbxwnsx+02Fwqm1KdoFoYF8QLhMLM3mFIhTIpoonREZoEPv+WM3FXmtSTGOd6ngN4HvaZM/MWkjRW81hEVPgnEayS35PDLURiX1XrM0G+zxGTXJHMqvHmYRgL+Qz5GYTS9Yokne82lk68+vnJQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-nonprod
    type: Opaque

