apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-nonprod
spec:
  encryptedData:
    DB_PASSWORD: AgBNTDl6pFKi/K/J6xNlg8OLm0pL4PVhC9VN9DfzK/7ujjdzyQCCNCuJFO17qPJi/bOaOcEb09msT26/FLFGIaJIj04HUIbLBslC7oZFMLuFmQzKXhYuyNzIvPtgz7WUkkA7au6IOPSnmnmlXMC/JaK/P4BcRx2gVs7fEKXsUabKqShR8mz6u3vb2+Sb7bDjTOT7nRZftKZLrgYCmszclugg4A3O6FnJhncBaRtHQBpZpOF4NpvdmBHjrgzwrWkwXnkNWoy5+ApY8cPDcrOlDzMbp1UWdNTEhHbpOJ/pwXekLSBvT/rWP+BYeTCq8yK1JUgIhZ0/snARW427Fxzafg5MY+PR1PXwv17H3t3i+ZixKEas68+uwEzCXdN6MFILBHgS9mAQ6gm1TuxRurnBSKwT8ILK6g4SOsAFE2mA026kBoJw+c3ILT6Fvs4sD8ZDAbMwDeLde70TBHuUHQ4VLxolBFuyck+e84xr8Vbq5SthGB/CYuqQF4wMFCaT7EbOXtTdXdz/CB2rx5xlOhvkMWvKJq9+7BmE6dpfQG+AW7nuQ2XJXCynm258mGBpoWkqhUkohmiV88w7UwuJ+Hbj6wIpK6ReJHeACKpBZiFBbjueqy0c4heYPhvKObS1qFCrRMpmFP1A/oahBWJFi0RCKz5AU5qcRBU05HFjcCJVbrG/M8Sbb2Y+WrgIdp5zyFXOmuvjXqSTQoeR2A==
    DB_USER: AgA7nCbx/bfuPZq/s7f+RlB7FRbLTQVZXSCIHqXUVpoYKIqO38VZ663/yooO8E0EZ2CIfL6+/WcKDH8jyPACWOIYZHGa+4l0W6jXmYRRtfzCbTWhdqT8VHQhwEECl49Lm0dUrwQU9nPtlQ9F1k+OH7By8nP34FIQwOSPDLUOLfutRd6mw+danTpt1h1EcW4El4xwl7WMi9a3jRsmu5bqSm7ufcxzXlhfUpw6YJzBQOmGOoLEvkyiyEFPBnXQL5jAZZroqZmTzt4z6tq1b4rEtk0c/wbCd+jcVfmbEkKC1/75jBoBy2FSQhbmy2hAJpvbtNF1bJcgX5U3jfpgwMtxQl7bwYwrNyXbTe9/hO9n+nO2N4HgTXfdnc5sEkhgKrVBIJDhVZ15H3xP3wPpfyMc+Gf5LYCR4DXo2/tZcPPbP62yHdq30beXpPpMC60DrvAX7aGGICVlqJGFlIF4GmHNyqnsr1wrTwMTOxY6k0AlIl5DjBGsJsbzbgR4M6loU9MKK7dPM61rrwVSgIv3xBGIsq11gNq4aN8NHMvTG8syc+ymNy56rYvshE3TTaG/wcjoWqwDRJjbtwteCI/DJedGTtgKce/rv2ExdSDAmod9YyBBhxuvJ6yTMjyM3qMVXPo90IwsJcwqPu23BOfVoS/34OwqNgCVWxkH4XIKLmCt3DgCtkOq1rjF1lM7kTgrHWs7AGkeZPGFlyd7ag==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-nonprod
    type: Opaque

